FROM node:15.4.0-alpine3.12

ARG USER=nextjs
ARG WORKDIR=/run/
ARG SHELL=/bin/sh

RUN set -x; \
    adduser \
        --home ${WORKDIR} \
        --shell ${SHELL} \
        --disabled-password \
        ${USER}
#     rm -rf .npm
    # npm install -g npm@7.1.2

RUN touch /var/log/npm && chown ${USER} /var/log/npm

USER ${USER}


WORKDIR ${WORKDIR}

RUN set -x; \
    npx create-next-app \
    app \
    --use-npm \
    --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"

WORKDIR ${WORKDIR}/${USER}

USER root

# Install TailwindCSS, gray-matter
RUN npm install \
    tailwindcss \
    postcss \
    autoprefixer \
    gray-matter

USER ${USER}

RUN rm -rf pages public


CMD /bin/sh
