FROM node:14.15.1-alpine3.12
# FROM node:15.4.0-alpine3.12
# 15.4.0 Doesn't work.

ARG USER=nextjs
ARG WORKDIR=/run/
ARG SHELL=/bin/sh

RUN set -aeux; \
    adduser \
        --home ${WORKDIR} \
        --shell ${SHELL} \
        --disabled-password \
        ${USER}

RUN touch /var/log/npm && chown ${USER} /var/log/npm

USER ${USER}

# WORKDIR ${WORKDIR}

# RUN set -aeux; \
#     npx create-next-app \
#     ${USER} \
#     --use-npm \
#     --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"

WORKDIR ${WORKDIR}/${USER}

# RUN set -aeux; \
#     rm -rf pages public ; \
#     touch tsconfig.json

# Install TailwindCSS, gray-matter, remark, date-fns
RUN set -aeux; \
    npm install --save-dev typescript @types/react @types/node ; \
    npm install \
    tailwindcss \
    postcss-preset-env \
    postcss-flexbugs-fixes \
    postcss \
    autoprefixer \
    gray-matter \
    remark \
    remark-html \
    date-fns

CMD set -aeux ; \
    /usr/local/bin/npm run dev
    # /usr/local/bin/npm run dev > /var/log/npm 2&>1 & /bin/sh
