FROM node:14.15.1-alpine3.12
# FROM node:15.4.0-alpine3.12
# 15.4.0 Doesn't work.

ARG USER=nextjs
ARG WORKDIR=/run
ARG SHELL=/bin/sh
ARG PERMISSIONS=og-rwx

RUN set -aeux; \
    # apk add --update curl vim; \
    adduser \
        --home ${WORKDIR} \
        --shell ${SHELL} \
        --disabled-password \
        ${USER}

RUN touch /var/log/npm && chown ${USER} /var/log/npm

WORKDIR ${WORKDIR}/${USER}

COPY --chown=${USER}:${USER} src/ .

RUN set -aeux; \
    npm install && \
    chown -R ${USER}:${USER} .
    # chown -R ${USER}:${USER} . && \
    # chmod -R ${PERMISSIONS} .

USER ${USER}

RUN set -aeux; \
    # npm run build
    npm run build && \
    chmod ${PERMISSIONS} .

CMD set -aeux ; \
    npm run dev

HEALTHCHECK --interval=10s CMD curl --fail localhost:3000 || exit 1