FROM node:14.15.1-alpine3.12
# FROM node:15.4.0-alpine3.12
# 15.4.0 Doesn't work.

ARG USER=nextjs
ARG WORKDIR=/run/
ARG SHELL=/bin/sh
ARG PERMISSIONS=og-rwx

RUN set -aeux; \
    # apk add --update curl vim; \
    adduser \
        --home ${WORKDIR} \
        --shell ${SHELL} \
        --disabled-password \
        ${USER}

RUN set -aeux; \
    touch /var/log/npm && \
    chown ${USER} /var/log/npm

WORKDIR ${WORKDIR}/${USER}

# Install TailwindCSS, gray-matter, remark, date-fns
RUN set -aeux; \
    npm install --save-dev typescript @types/react @types/node ; \
    npm install \
    tailwindcss \
    postcss-preset-env \
    postcss-flexbugs-fixes \
    postcss \
    autoprefixer \
    gray-matter \
    remark \
    remark-html \
    date-fns

RUN chown -R ${USER}:${USER} . ; \
    chmod -R ${PERMISSIONS} .

USER ${USER}

CMD set -aeux ; \
    npm install && \
    npm run build && \
    npm run dev
    # /usr/local/bin/npm run dev > /var/log/npm 2&>1 & /bin/sh
